# Generated by Django 2.2.5 on 2019-09-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('mob_no', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
