# Generated by Django 2.2.5 on 2019-09-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_version_1', '0002_auto_20190920_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('source', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('no_of_seats', models.IntegerField()),
                ('time', models.FloatField()),
                ('description', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'bus',
            },
        ),
    ]
