# Generated by Django 2.2.5 on 2019-09-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_version_1', '0003_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='availability',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
