# Generated by Django 2.2.5 on 2019-09-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_version_1', '0005_auto_20190923_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='available_seats',
            field=models.IntegerField(default=models.IntegerField()),
        ),
    ]
