# Generated by Django 2.2.5 on 2019-10-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_version_1', '0006_auto_20190924_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='no_of_columns',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bus',
            name='no_of_rows',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_status',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
